### ISSUE TITLE
Whitelist a user agent?

### ISSUE THREAD

**Issue by pjv** [mitchellkrogza/nginx-ultimate-bad-bot-blocker#62]
I've run across a situation where a partial user agent string that is in the global blacklist is blocking a user agent that I need to whitelist.

The line in the global blacklist looks like this:

`"~*Disco"		3;`

In my case, the user agent string that I need to whitelist (currently blocked by the rule above) looks like this:

`Discourse Forum Onebox v1.9.0.beta3`

I tried putting
`"~*Disco"		0;`

into `whitelist-domains.conf` but that didn’t' work.

Is there any correct way to whitelist a particular user agent string that is on the global blocklist, or override a blocked user agent string other than directly editing the global blocklist file (which would then make automatic updates un-usable)?

**Comment by pjv** [comment]
Never mind - I discovered that you can whitelist user agents with the `blacklist-user-agents.conf` file.

In my case adding the string:
`"~*Discourse"    0;`

to that file solved the above issue.

**Comment by mitchellkrogza** [comment]
Thanks @pjv I will look into this for a regex change exact matching and not partial. But yes you can by whitelist using the blacklist-user-agents.conf file. Will test this tomorrow and fix where necessary to avoid partial matching.

**Comment by mitchellkrogza** [comment]
@pjv please try pull latest update. Regex pattern matching on User-Agents has been changed to use word boundaries. So now a bot like "Disco" will not cause a false positive on "Discourse". 
Fixed in https://github.com/mitchellkrogza/nginx-ultimate-bad-bot-blocker/commit/327346d15eccbf6bc27b62785e973bcce53c7ad5

**Comment by mitchellkrogza** [comment]
Commenting and examples of regex patterns in `blacklist-user-agents.conf` updated in https://github.com/mitchellkrogza/nginx-ultimate-bad-bot-blocker/commit/0b7141119ccf11198dade6d97754e979bc51ebc0

**Comment by pjv** [comment]
Sorry for the delay in responding. For my use-case detailed above, the new word-bounded regexes for the user agent matching seems to work. I was able to comment out my white listing of `Discourse` and still not have it be blocked.

Good job @mitchellkrogza.

**Comment by mitchellkrogza** [comment]
Awesome @pjv so glad, your issue has helped strengthen and improve the blocker against false positives so thank you again for reporting it. Enjoy and thanks for the support.
